# Generated by Django 6.0.6 on 2026-06-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.skill'),
            preserve_default=False,
        ),
    ]
